services:
  db:
    image: postgres:13.10
    env_file: ./src/.env
    volumes:
      - test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  src:
    depends_on:
        - db
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: ./src/.env
    command: sh -c "poetry run alembic upgrade head &&
      poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000
      "

volumes:
   test: